IMAGE:
  WIDTH: 640
  HEIGHT: 480
  MINTHRES: 150
  MAXTHRES: 255

  SRCPT_X0: 70
  SRCPT_X1: 440
  SRCPT_X2: 480
  SRCPT_X3: 40

  SRCPT_Y0: 390
  SRCPT_Y1: 390
  SRCPT_Y2: 430
  SRCPT_Y3: 430
  
  DSTPT_X0: 0
  DSTPT_X1: 479
  DSTPT_X2: 479
  DSTPT_X3: 0
  DSTPT_Y0: 0
  DSTPT_Y1: 0
  DSTPT_Y2: 639
  DSTPT_Y3: 639

  BLURSIGMA: 1.0
  # find your ROI parameter.

XYCAR:
  START_SPEED: 10.0
  MAX_SPEED: 15.0
  MIN_SPEED: 9.0
  SPEED_CONTROL_THRESHOLD: 8.0
  ACCELERATION_STEP: 0.50
  DECELERATION_STEP: 0.50
  # find your parameter.

# If you want to use other control methods, Change PID to another control methods.
PID:
  P_GAIN: 0.2
  I_GAIN: 0.0001
  D_GAIN: 0.02
  # find your parameter.

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 1

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1000

DEBUG: true
