IMAGE:
  WIDTH: 640
  HEIGHT: 480
  Y_OFFSET: 440
  # find your ROI parameter.

XYCAR:
  START_SPEED: 8.0
  MAX_SPEED: 13.0
  MIN_SPEED: 5.0
  SPEED_CONTROL_THRESHOLD: 30.0
  ACCELERATION_STEP: 1.0
  DECELERATION_STEP: 0.8
  # find your parameter.

# If you want to use other control methods, Change PID to another control methods.
PID:
  P_GAIN: 0.25
  I_GAIN: 0.0000
  D_GAIN: 0.03
  # find your parameter.

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 20

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

DEBUG: true
