IMAGE:
  WIDTH: 640
  HEIGHT: 480
  MINTHRES: 150
  MAXTHRES: 255

  SRCPT_X0: 100
  SRCPT_X1: 440
  SRCPT_X2: 500
  SRCPT_X3: 30
  SRCPT_Y0: 350
  SRCPT_Y1: 350
  SRCPT_Y2: 390
  SRCPT_Y3: 390
  
  DSTPT_X0: 0
  DSTPT_X1: 479
  DSTPT_X2: 479
  DSTPT_X3: 0
  DSTPT_Y0: 0
  DSTPT_Y1: 0
  DSTPT_Y2: 639
  DSTPT_Y3: 639

  BLURSIGMA: 1.0
  # find your ROI parameter.

XYCAR:
  START_SPEED: 0.0
  MAX_SPEED: 0.0
  MIN_SPEED: 0.0
  SPEED_CONTROL_THRESHOLD: 0.0
  ACCELERATION_STEP: 0.00
  DECELERATION_STEP: 0.0
  # find your parameter.

# If you want to use other control methods, Change PID to another control methods.
PID:
  P_GAIN: 0.0
  I_GAIN: 0.0000
  D_GAIN: 0.00
  # find your parameter.

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

DEBUG: true
